"""
UK SIC 2007 code → description lookup.
Source: UK SIC 2007 (ONS). Common codes used in expansion applications.
"""

SIC_DESCRIPTIONS = {
    # A — Agriculture
    "01110": "Growing of Cereals (except Rice), Leguminous Crops and Oil Seeds",
    "01410": "Raising of Dairy Cattle",
    "01500": "Mixed Farming",

    # B — Mining & Quarrying
    "06100": "Extraction of Crude Petroleum",
    "06200": "Extraction of Natural Gas",

    # C — Manufacturing
    "10110": "Processing and Preserving of Meat",
    "10200": "Processing and Preserving of Fish, Crustaceans and Molluscs",
    "10310": "Processing and Preserving of Potatoes",
    "10410": "Manufacture of Oils and Fats",
    "10510": "Operation of Dairies and Cheese Making",
    "10610": "Manufacture of Grain Mill Products",
    "10710": "Manufacture of Bread; Manufacture of Fresh Pastry Goods and Cakes",
    "10720": "Manufacture of Rusks and Biscuits; Manufacture of Preserved Pastry Goods and Cakes",
    "10810": "Manufacture of Sugar",
    "10890": "Manufacture of Other Food Products",
    "11010": "Distilling, Rectifying and Blending of Spirits",
    "11050": "Manufacture of Beer",
    "13100": "Preparation and Spinning of Textile Fibres",
    "13200": "Weaving of Textiles",
    "13910": "Manufacture of Knitted and Crocheted Fabrics",
    "13920": "Manufacture of Made-up Textile Articles, except Apparel",
    "14110": "Manufacture of Leather Clothes",
    "14120": "Manufacture of Workwear",
    "14130": "Manufacture of Other Outerwear",
    "14190": "Manufacture of Other Wearing Apparel and Accessories",
    "14200": "Manufacture of Articles of Fur",
    "14310": "Manufacture of Knitted and Crocheted Hosiery",
    "15110": "Tanning and Dressing of Leather",
    "15120": "Manufacture of Luggage, Handbags and the Like, Saddlery and Harness",
    "15200": "Manufacture of Footwear",
    "16100": "Sawmilling and Planing of Wood",
    "16210": "Manufacture of Veneer Sheets and Wood-based Panels",
    "17110": "Manufacture of Pulp",
    "17120": "Manufacture of Paper and Paperboard",
    "17210": "Manufacture of Corrugated Paper and Paperboard",
    "18110": "Printing of Newspapers",
    "18120": "Printing (other than Newspapers)",
    "19100": "Manufacture of Coke Oven Products",
    "19200": "Manufacture of Refined Petroleum Products",
    "20110": "Manufacture of Industrial Gases",
    "20120": "Manufacture of Dyes and Pigments",
    "20130": "Manufacture of Other Inorganic Basic Chemicals",
    "20140": "Manufacture of Other Organic Basic Chemicals",
    "20150": "Manufacture of Fertilisers and Nitrogen Compounds",
    "20160": "Manufacture of Plastics in Primary Forms",
    "20170": "Manufacture of Synthetic Rubber in Primary Forms",
    "20200": "Manufacture of Pesticides and Other Agrochemical Products",
    "20300": "Manufacture of Paints, Varnishes and Similar Coatings",
    "20410": "Manufacture of Soap and Detergents, Cleaning and Polishing Preparations",
    "20420": "Manufacture of Perfumes and Toilet Preparations",
    "20510": "Manufacture of Explosives",
    "20590": "Manufacture of Other Chemical Products",
    "21100": "Manufacture of Basic Pharmaceutical Products",
    "21200": "Manufacture of Pharmaceutical Preparations",
    "22110": "Manufacture of Rubber Tyres and Tubes",
    "22190": "Manufacture of Other Rubber Products",
    "22210": "Manufacture of Plastic Plates, Sheets, Tubes and Profiles",
    "22220": "Manufacture of Plastic Packing Goods",
    "22290": "Manufacture of Other Plastic Products",
    "23110": "Manufacture of Flat Glass",
    "23200": "Manufacture of Refractory Products",
    "23610": "Manufacture of Concrete Products for Construction Purposes",
    "23700": "Cutting, Shaping and Finishing of Stone",
    "23900": "Manufacture of Abrasive Products and Non-metallic Mineral Products",
    "24100": "Manufacture of Basic Iron and Steel",
    "24200": "Manufacture of Steel Tubes, Pipes, Hollow Profiles and Related Fittings",
    "25110": "Manufacture of Metal Structures and Parts of Structures",
    "25120": "Manufacture of Doors and Windows of Metal",
    "25500": "Forging, Pressing, Stamping and Roll-forming of Metal",
    "25610": "Treatment and Coating of Metals",
    "25620": "Machining",
    "25710": "Manufacture of Cutlery",
    "25720": "Manufacture of Locks and Hinges",
    "25730": "Manufacture of Tools",
    "25910": "Manufacture of Steel Drums and Similar Containers",
    "25990": "Manufacture of Other Fabricated Metal Products",
    "26110": "Manufacture of Electronic Components",
    "26120": "Manufacture of Loaded Electronic Boards",
    "26200": "Manufacture of Computers and Peripheral Equipment",
    "26300": "Manufacture of Communication Equipment",
    "26400": "Manufacture of Consumer Electronics",
    "26510": "Manufacture of Instruments and Appliances for Measuring, Testing and Navigation",
    "26600": "Manufacture of Irradiation, Electromedical and Electrotherapeutic Equipment",
    "26700": "Manufacture of Optical Instruments and Photographic Equipment",
    "26800": "Manufacture of Magnetic and Optical Media",
    "27110": "Manufacture of Electric Motors, Generators and Transformers",
    "27200": "Manufacture of Batteries and Accumulators",
    "27310": "Manufacture of Fibre Optic Cables",
    "27320": "Manufacture of Other Electronic and Electric Wires and Cables",
    "27330": "Manufacture of Wiring Devices",
    "27400": "Manufacture of Electric Lighting Equipment",
    "27510": "Manufacture of Electric Domestic Appliances",
    "27520": "Manufacture of Non-electric Domestic Appliances",
    "27900": "Manufacture of Other Electrical Equipment",
    "28110": "Manufacture of Engines and Turbines",
    "28120": "Manufacture of Fluid Power Equipment",
    "28150": "Manufacture of Bearings, Gears, Gearing and Driving Elements",
    "28160": "Manufacture of Lifting and Handling Equipment",
    "28210": "Manufacture of Ovens, Furnaces and Furnace Burners",
    "28220": "Manufacture of Lifting and Handling Equipment",
    "28230": "Manufacture of Office Machinery and Equipment (except Computers and Peripheral Equipment)",
    "28290": "Manufacture of Other General-purpose Machinery",
    "28300": "Manufacture of Agricultural and Forestry Machinery",
    "28410": "Manufacture of Metal Forming Machinery",
    "28490": "Manufacture of Other Machine Tools",
    "28910": "Manufacture of Machinery for Metallurgy",
    "28920": "Manufacture of Machinery for Mining, Quarrying and Construction",
    "28930": "Manufacture of Machinery for Food, Beverage and Tobacco Processing",
    "28940": "Manufacture of Machinery for Textile, Apparel and Leather Production",
    "28990": "Manufacture of Other Special-purpose Machinery",
    "29100": "Manufacture of Motor Vehicles",
    "29200": "Manufacture of Bodies (Coachwork) for Motor Vehicles",
    "29310": "Manufacture of Electrical and Electronic Equipment for Motor Vehicles",
    "29320": "Manufacture of Other Parts and Accessories for Motor Vehicles",
    "30110": "Building of Ships and Floating Structures",
    "30120": "Building of Pleasure and Sporting Boats",
    "30200": "Manufacture of Railway Locomotives and Rolling Stock",
    "30300": "Manufacture of Air and Spacecraft and Related Machinery",
    "30400": "Manufacture of Military Fighting Vehicles",
    "30910": "Manufacture of Motorcycles",
    "30920": "Manufacture of Bicycles and Invalid Carriages",
    "30990": "Manufacture of Other Transport Equipment",
    "31010": "Manufacture of Office and Shop Furniture",
    "31020": "Manufacture of Kitchen Furniture",
    "31030": "Manufacture of Mattresses",
    "31090": "Manufacture of Other Furniture",
    "32110": "Striking of Coins",
    "32120": "Manufacture of Jewellery and Related Articles",
    "32130": "Manufacture of Imitation Jewellery and Related Articles",
    "32200": "Manufacture of Musical Instruments",
    "32300": "Manufacture of Sports Goods",
    "32400": "Manufacture of Games and Toys",
    "32500": "Manufacture of Medical and Dental Instruments and Supplies",
    "32910": "Manufacture of Brooms and Brushes",
    "32990": "Other Manufacturing",

    # D — Electricity & Gas
    "35110": "Production of Electricity",
    "35120": "Transmission of Electricity",
    "35130": "Distribution of Electricity",
    "35140": "Trade of Electricity",
    "35210": "Manufacture of Gas",
    "35220": "Distribution of Gaseous Fuels Through Mains",
    "35230": "Trade of Gas Through Mains",
    "35300": "Steam and Air Conditioning Supply",

    # E — Water & Waste
    "36000": "Water Collection, Treatment and Supply",
    "37000": "Sewerage",
    "38110": "Collection of Non-hazardous Waste",
    "38120": "Collection of Hazardous Waste",
    "38210": "Treatment and Disposal of Non-hazardous Waste",
    "38220": "Treatment and Disposal of Hazardous Waste",
    "38310": "Dismantling of Wrecks",
    "38320": "Recovery of Sorted Materials",
    "39000": "Remediation Activities and Other Waste Management Services",

    # F — Construction
    "41100": "Development of Building Projects",
    "41200": "Construction of Residential and Non-residential Buildings",
    "42110": "Construction of Roads and Motorways",
    "42120": "Construction of Railways and Underground Railways",
    "42130": "Construction of Bridges and Tunnels",
    "42210": "Construction of Utility Projects for Fluids",
    "42220": "Construction of Utility Projects for Electricity and Telecommunications",
    "42910": "Construction of Water Projects",
    "42990": "Construction of Other Civil Engineering Projects",
    "43110": "Demolition",
    "43120": "Site Preparation",
    "43130": "Test Drilling and Boring",
    "43210": "Electrical Installation",
    "43220": "Plumbing, Heat and Air-conditioning Installation",
    "43290": "Other Construction Installation",
    "43310": "Plastering",
    "43320": "Joinery Installation",
    "43330": "Floor and Wall Covering",
    "43341": "Painting",
    "43342": "Glazing",
    "43390": "Other Building Completion and Finishing",
    "43910": "Roofing Activities",
    "43991": "Scaffold Erection",
    "43999": "Other Specialised Construction Activities",

    # G — Wholesale and Retail Trade
    "45111": "Sale of New Cars and Light Motor Vehicles",
    "45112": "Sale of Used Cars and Light Motor Vehicles",
    "45190": "Sale of Other Motor Vehicles",
    "45200": "Maintenance and Repair of Motor Vehicles",
    "45310": "Wholesale Trade of Motor Vehicle Parts and Accessories",
    "45320": "Retail Trade of Motor Vehicle Parts and Accessories",
    "45400": "Sale, Maintenance and Repair of Motorcycles and Related Parts",
    "46110": "Agents Involved in the Sale of Agricultural Raw Materials, Live Animals, Textile Raw Materials and Semi-finished Goods",
    "46120": "Agents Involved in the Sale of Fuels, Ores, Metals and Industrial Chemicals",
    "46130": "Agents Involved in the Sale of Timber and Building Materials",
    "46140": "Agents Involved in the Sale of Machinery, Industrial Equipment, Ships and Aircraft",
    "46150": "Agents Involved in the Sale of Furniture, Household Goods, Hardware and Ironmongery",
    "46160": "Agents Involved in the Sale of Textiles, Clothing, Fur, Footwear and Leather Goods",
    "46170": "Agents Involved in the Sale of Food, Beverages and Tobacco",
    "46180": "Agents Specialised in the Sale of Other Particular Products",
    "46190": "Agents Involved in the Sale of a Variety of Goods",
    "46210": "Wholesale of Grain, Unmanufactured Tobacco, Seeds and Animal Feeds",
    "46220": "Wholesale of Flowers and Plants",
    "46230": "Wholesale of Live Animals",
    "46240": "Wholesale of Hides, Skins and Leather",
    "46310": "Wholesale of Fruit and Vegetables",
    "46320": "Wholesale of Meat and Meat Products",
    "46330": "Wholesale of Dairy Products, Eggs and Edible Oils and Fats",
    "46340": "Wholesale of Beverages",
    "46350": "Wholesale of Tobacco Products",
    "46360": "Wholesale of Sugar and Chocolate and Sugar Confectionery",
    "46370": "Wholesale of Coffee, Tea, Cocoa and Spices",
    "46380": "Wholesale of Other Food, Including Fish, Crustaceans and Molluscs",
    "46390": "Non-Specialised Wholesale of Food, Beverages and Tobacco",
    "46410": "Wholesale of Textiles",
    "46420": "Wholesale of Clothing and Footwear",
    "46430": "Wholesale of Electrical Household Appliances",
    "46440": "Wholesale of China and Glassware and Cleaning Materials",
    "46450": "Wholesale of Perfume and Cosmetics",
    "46460": "Wholesale of Pharmaceutical Goods",
    "46470": "Wholesale of Furniture, Carpets and Lighting Equipment",
    "46480": "Wholesale of Watches and Jewellery",
    "46490": "Wholesale of Other Household Goods",
    "46510": "Wholesale of Computers, Computer Peripheral Equipment and Software",
    "46520": "Wholesale of Electronic and Telecommunications Equipment and Parts",
    "46610": "Wholesale of Agricultural Machinery, Equipment and Supplies",
    "46620": "Wholesale of Machine Tools",
    "46630": "Wholesale of Mining, Construction and Civil Engineering Machinery",
    "46640": "Wholesale of Machinery for the Textile Industry and of Sewing and Knitting Machines",
    "46650": "Wholesale of Office Furniture",
    "46660": "Wholesale of Other Office Machinery and Equipment",
    "46690": "Wholesale of Other Machinery and Equipment",
    "46710": "Wholesale of Solid, Liquid and Gaseous Fuels and Related Products",
    "46720": "Wholesale of Metals and Metal Ores",
    "46730": "Wholesale of Wood, Construction Materials and Sanitary Equipment",
    "46740": "Wholesale of Hardware, Plumbing and Heating Equipment and Supplies",
    "46750": "Wholesale of Chemical Products",
    "46760": "Wholesale of Other Intermediate Products",
    "46770": "Wholesale of Waste and Scrap",
    "46900": "Non-Specialised Wholesale Trade",
    "47110": "Retail Sale in Non-specialised Stores with Food, Beverages or Tobacco Predominating",
    "47190": "Other Retail Sale in Non-specialised Stores",
    "47210": "Retail Sale of Fruit and Vegetables in Specialised Stores",
    "47220": "Retail Sale of Meat and Meat Products in Specialised Stores",
    "47230": "Retail Sale of Fish, Crustaceans and Molluscs in Specialised Stores",
    "47240": "Retail Sale of Bread, Cakes, Flour Confectionery and Sugar Confectionery in Specialised Stores",
    "47250": "Retail Sale of Beverages in Specialised Stores",
    "47260": "Retail Sale of Tobacco Products in Specialised Stores",
    "47290": "Other Retail Sale of Food in Specialised Stores",
    "47300": "Retail Sale of Automotive Fuel in Specialised Stores",
    "47410": "Retail Sale of Computers, Peripheral Units and Software in Specialised Stores",
    "47421": "Retail Sale of Mobile Telephones",
    "47429": "Retail Sale of Telecommunications Equipment",
    "47430": "Retail Sale of Audio and Video Equipment in Specialised Stores",
    "47510": "Retail Sale of Textiles in Specialised Stores",
    "47520": "Retail Sale of Hardware, Paints and Glass in Specialised Stores",
    "47530": "Retail Sale of Carpets, Rugs, Wall and Floor Coverings in Specialised Stores",
    "47540": "Retail Sale of Electrical Household Appliances in Specialised Stores",
    "47591": "Retail Sale of Musical Instruments and Scores",
    "47599": "Retail of Furniture, Lighting and Similar in Specialised Store",
    "47610": "Retail Sale of Books in Specialised Stores",
    "47620": "Retail Sale of Newspapers and Stationery in Specialised Stores",
    "47630": "Retail Sale of Music and Video Recordings in Specialised Stores",
    "47640": "Retail Sale of Sports Goods, Fishing Gear, Camping Goods, Boats and Bicycles",
    "47650": "Retail Sale of Games and Toys in Specialised Stores",
    "47710": "Retail Sale of Clothing in Specialised Stores",
    "47720": "Retail Sale of Footwear and Leather Goods in Specialised Stores",
    "47730": "Dispensing Chemist in Specialised Stores",
    "47740": "Retail Sale of Medical and Orthopaedic Goods in Specialised Stores",
    "47750": "Retail Sale of Cosmetic and Toilet Articles in Specialised Stores",
    "47760": "Retail Sale of Flowers, Plants, Seeds, Fertilisers, Pet Animals and Pet Food in Specialised Stores",
    "47770": "Retail Sale of Watches and Jewellery in Specialised Stores",
    "47781": "Retail Sale in Commercial Art Galleries",
    "47782": "Retail Sale by Opticians",
    "47789": "Other Retail Sale of New Goods in Specialised Stores",
    "47791": "Retail Sale of Antiques, including Antique Books in Stores",
    "47799": "Retail Sale of Second-hand Goods (other than Antiques and Second-hand Books) in Stores",
    "47810": "Retail Sale via Stalls and Markets of Food, Beverages and Tobacco Products",
    "47820": "Retail Sale via Stalls and Markets of Textiles, Clothing and Footwear",
    "47890": "Retail Sale via Stalls and Markets of Other Goods",
    "47910": "Retail Sale via Mail Order Houses or via Internet",
    "47990": "Other Retail Sale Not in Stores, Stalls or Markets",

    # H — Transportation and Storage
    "49100": "Passenger Rail Transport, Interurban",
    "49200": "Freight Rail Transport",
    "49310": "Urban and Suburban Passenger Land Transport",
    "49320": "Taxi Operation",
    "49390": "Other Passenger Land Transport",
    "49410": "Freight Transport by Road",
    "49420": "Removal Services",
    "49500": "Transport via Pipeline",
    "50100": "Sea and Coastal Passenger Water Transport",
    "50200": "Sea and Coastal Freight Water Transport",
    "50300": "Inland Passenger Water Transport",
    "50400": "Inland Freight Water Transport",
    "51100": "Passenger Air Transport",
    "51210": "Freight Air Transport",
    "51220": "Space Transport",
    "52100": "Warehousing and Storage",
    "52211": "Operation of Rail Freight Terminals",
    "52212": "Operation of Rail Passenger Facilities at Railway Stations",
    "52213": "Operation of Bus and Coach Passenger Facilities at Bus and Coach Stations",
    "52219": "Other Service Activities Incidental to Land Transportation",
    "52220": "Service Activities Incidental to Water Transportation",
    "52230": "Service Activities Incidental to Air Transportation",
    "52240": "Cargo Handling",
    "52290": "Other Supporting Transport Activities",
    "53100": "Postal Activities under Universal Service Obligation",
    "53200": "Other Postal and Courier Activities",

    # I — Accommodation and Food
    "55100": "Hotels and Similar Accommodation",
    "55201": "Holiday Centres and Villages",
    "55202": "Youth Hostels",
    "55209": "Other Holiday and Other Short-stay Accommodation",
    "55300": "Recreational Vehicle Parks, Trailer Parks and Camping Grounds",
    "55900": "Other Accommodation",
    "56101": "Licensed Restaurants",
    "56102": "Unlicensed Restaurants and Cafes",
    "56103": "Take-away Food Shops and Mobile Food Stands",
    "56210": "Event Catering Activities",
    "56290": "Other Food Service Activities",
    "56301": "Licensed Clubs",
    "56302": "Public Houses and Bars",

    # J — Information and Communication
    "58110": "Book Publishing",
    "58120": "Publishing of Directories and Mailing Lists",
    "58130": "Publishing of Newspapers",
    "58142": "Publishing of Consumer and Business Journals and Periodicals",
    "58190": "Other Publishing Activities",
    "58210": "Publishing of Computer Games",
    "58290": "Other Software Publishing",
    "59111": "Motion Picture Production Activities",
    "59112": "Video Production Activities",
    "59113": "Television Programme Production Activities",
    "59120": "Motion Picture, Video and Television Programme Post-production Activities",
    "59130": "Motion Picture, Video and Television Programme Distribution Activities",
    "59140": "Motion Picture Projection Activities",
    "59200": "Sound Recording and Music Publishing Activities",
    "60100": "Radio Broadcasting",
    "60200": "Television Programming and Broadcasting Activities",
    "61100": "Wired Telecommunications Activities",
    "61200": "Wireless Telecommunications Activities",
    "61300": "Satellite Telecommunications Activities",
    "61900": "Other Telecommunications Activities",
    "62011": "Ready-made Interactive Leisure and Entertainment Software Development",
    "62012": "Business and Domestic Software Development",
    "62020": "Information Technology Consultancy Activities",
    "62030": "Computer Facilities Management Activities",
    "62090": "Other Information Technology Service Activities",
    "63110": "Data Processing, Hosting and Related Activities",
    "63120": "Web Portals",
    "63910": "News Agency Activities",
    "63990": "Other Information Service Activities",

    # K — Financial and Insurance
    "64110": "Central Banking",
    "64190": "Other Monetary Intermediation",
    "64201": "Activities of Agricultural Holding Companies",
    "64202": "Activities of Production Holding Companies",
    "64203": "Activities of Construction Holding Companies",
    "64204": "Activities of Distribution Holding Companies",
    "64205": "Activities of Financial Services Holding Companies",
    "64209": "Activities of Other Holding Companies",
    "64301": "Activities of Investment Trusts",
    "64302": "Activities of Unit Trusts",
    "64303": "Activities of Venture and Development Capital Companies",
    "64304": "Activities of Open-Ended Investment Companies",
    "64305": "Activities of Property Unit Trusts",
    "64306": "Activities of Real Estate Investment Trusts",
    "64910": "Financial Leasing",
    "64921": "Credit Granting by Non-deposit Taking Finance Houses and Other Specialist Consumer Credit Grantors",
    "64922": "Activities of Mortgage Finance Companies",
    "64929": "Other Credit Granting",
    "64991": "Security Dealing on Own Account",
    "64992": "Factoring",
    "64999": "Other Financial Service Activities, Except Insurance and Pension Funding",
    "65110": "Life Insurance",
    "65120": "Non-life Insurance",
    "65200": "Reinsurance",
    "65300": "Pension Funding",
    "66110": "Administration of Financial Markets",
    "66120": "Security and Commodity Contracts Dealing Activities",
    "66190": "Other Activities Auxiliary to Financial Services, Except Insurance and Pension Funding",
    "66210": "Risk and Damage Evaluation",
    "66220": "Activities of Insurance Agents and Brokers",
    "66290": "Other Activities Auxiliary to Insurance and Pension Funding",
    "66300": "Fund Management Activities",

    # L — Real Estate
    "68100": "Buying and Selling of Own Real Estate",
    "68201": "Renting and Operating of Housing Association Real Estate",
    "68202": "Letting and Operating of Conference and Exhibition Centres",
    "68209": "Other Letting and Operating of Own or Leased Real Estate",
    "68310": "Real Estate Agencies",
    "68320": "Management of Real Estate on a Fee or Contract Basis",

    # M — Professional, Scientific and Technical
    "69101": "Barristers at Law",
    "69102": "Solicitors",
    "69109": "Activities of Patent and Copyright Agents; Other Legal Activities",
    "69201": "Accounting and Auditing Activities",
    "69202": "Bookkeeping Activities",
    "69203": "Tax Consultancy",
    "70100": "Activities of Head Offices",
    "70210": "Public Relations and Communications Activities",
    "70221": "Financial Management",
    "70229": "Management Consultancy Activities other than Financial Management",
    "71111": "Architectural Activities",
    "71112": "Urban Planning and Landscape Architectural Activities",
    "71121": "Engineering Design Activities for Industrial Process and Production",
    "71122": "Engineering Related Scientific and Technical Consulting Activities",
    "71129": "Other Engineering Activities",
    "71200": "Technical Testing and Analysis",
    "72110": "Research and Experimental Development on Biotechnology",
    "72190": "Other Research and Experimental Development on Natural Sciences and Engineering",
    "72200": "Research and Experimental Development on Social Sciences and Humanities",
    "73110": "Advertising Agencies",
    "73120": "Media Representation Services",
    "73200": "Market Research and Public Opinion Polling",
    "74100": "Specialised Design Activities",
    "74201": "Portrait Photographic Activities",
    "74202": "Other Specialist Photography",
    "74203": "Film Processing",
    "74209": "Photographic Activities, Not Elsewhere Classified",
    "74300": "Translation and Interpretation Activities",
    "74901": "Environmental Consulting Activities",
    "74902": "Quantity Surveying Activities",
    "74909": "Other Professional, Scientific and Technical Activities not Elsewhere Classified",
    "75000": "Veterinary Activities",

    # N — Administrative and Support Services
    "77110": "Renting and Leasing of Cars and Light Motor Vehicles",
    "77120": "Renting and Leasing of Trucks and Other Heavy Vehicles",
    "77210": "Renting and Leasing of Recreational and Sports Goods",
    "77220": "Renting of Video Tapes and Disks",
    "77290": "Renting and Leasing of Other Personal and Household Goods",
    "77310": "Renting and Leasing of Agricultural Machinery and Equipment",
    "77320": "Renting and Leasing of Construction and Civil Engineering Machinery and Equipment",
    "77330": "Renting and Leasing of Office Machinery and Equipment (Including Computers)",
    "77340": "Renting and Leasing of Water Transport Equipment",
    "77350": "Renting and Leasing of Air Transport Equipment",
    "77390": "Renting and Leasing of Other Machinery, Equipment and Tangible Goods",
    "77400": "Leasing of Intellectual Property and Similar Products, Except Copyrighted Works",
    "78100": "Activities of Employment Placement Agencies",
    "78200": "Temporary Employment Agency Activities",
    "78300": "Human Resources Provision and Management of Human Resources Functions",
    "79110": "Travel Agency Activities",
    "79120": "Tour Operator Activities",
    "79901": "Activities of Tourist Guides",
    "79909": "Other Reservation Service and Related Activities",
    "80100": "Private Security Activities",
    "80200": "Security Systems Service Activities",
    "80300": "Investigation Activities",
    "81100": "Combined Facilities Support Activities",
    "81210": "General Cleaning of Buildings",
    "81221": "Window Cleaning Services",
    "81222": "Specialised Cleaning Services",
    "81223": "Furnace and Chimney Cleaning Services",
    "81229": "Other Building and Industrial Cleaning Activities",
    "81291": "Disinfecting and Exterminating Services",
    "81299": "Other Cleaning Services",
    "81300": "Landscape Service Activities",
    "82110": "Combined Office Administrative Service Activities",
    "82190": "Photocopying, Document Preparation and other Specialised Office Support Activities",
    "82200": "Activities of Call Centres",
    "82301": "Activities of Exhibition and Fair Organisers",
    "82302": "Activities of Conference Organisers",
    "82911": "Activities of Collection Agencies",
    "82912": "Activities of Credit Bureaus",
    "82920": "Packaging Activities",
    "82990": "Other Business Support Service Activities",

    # O — Public Administration
    "84110": "General Public Administration Activities",
    "84120": "Regulation of the Activities of Providing Health Care, Education, Cultural Services and Other Social Services, Excluding Social Security",
    "84130": "Regulation of and Contribution to More Efficient Operation of Businesses",
    "84210": "Foreign Affairs",
    "84220": "Defence Activities",
    "84230": "Justice and Judicial Activities",
    "84240": "Public Order and Safety Activities",
    "84250": "Fire Service Activities",
    "84300": "Compulsory Social Security Activities",

    # P — Education
    "85100": "Pre-primary Education",
    "85200": "Primary Education",
    "85310": "General Secondary Education",
    "85320": "Technical and Vocational Secondary Education",
    "85410": "Post-secondary Non-tertiary Education",
    "85421": "First-degree Level Higher Education",
    "85422": "Post-graduate Level Higher Education",
    "85510": "Sports and Recreation Education",
    "85520": "Cultural Education",
    "85530": "Driving School Activities",
    "85590": "Other Education",
    "85600": "Educational Support Activities",

    # Q — Human Health and Social Work
    "86101": "Hospital Activities",
    "86102": "Medical Nursing Home Activities",
    "86210": "General Medical Practice Activities",
    "86220": "Specialist Medical Practice Activities",
    "86230": "Dental Practice Activities",
    "86290": "Other Human Health Activities",
    "86900": "Other Human Health Activities",
    "87100": "Residential Nursing Care Activities",
    "87200": "Residential Care Activities for Learning Difficulties, Mental Health and Substance Abuse",
    "87300": "Residential Care Activities for the Elderly and Disabled",
    "87900": "Other Residential Care Activities",
    "88100": "Social Work Activities without Accommodation for the Elderly and Disabled",
    "88910": "Child Day-care Activities",
    "88990": "Other Social Work Activities without Accommodation",

    # R — Arts, Entertainment and Recreation
    "90010": "Performing Arts",
    "90020": "Support Activities to Performing Arts",
    "90030": "Artistic Creation",
    "90040": "Operation of Arts Facilities",
    "91011": "Library Activities",
    "91012": "Archive Activities",
    "91020": "Museum Activities",
    "91030": "Operation of Historical Sites and Buildings and Similar Visitor Attractions",
    "91040": "Botanical and Zoological Gardens and Nature Reserve Activities",
    "92000": "Gambling and Betting Activities",
    "93110": "Operation of Sports Facilities",
    "93120": "Activities of Sport Clubs",
    "93130": "Fitness Facilities",
    "93191": "Activities of Racing and Pony Clubs",
    "93199": "Other Sports Activities",
    "93210": "Activities of Amusement Parks and Theme Parks",
    "93290": "Other Amusement and Recreation Activities",

    # S — Other Service Activities
    "94110": "Activities of Business and Employers Membership Organisations",
    "94120": "Activities of Professional Membership Organisations",
    "94200": "Activities of Trade Unions",
    "94910": "Activities of Religious Organisations",
    "94920": "Activities of Political Organisations",
    "94990": "Activities of Other Membership Organisations",
    "95110": "Repair of Computers and Peripheral Equipment",
    "95120": "Repair of Communication Equipment",
    "95210": "Repair of Consumer Electronics",
    "95220": "Repair of Household Appliances and Home and Garden Equipment",
    "95230": "Repair of Footwear and Leather Goods",
    "95240": "Repair of Furniture and Home Furnishings",
    "95250": "Repair of Watches, Clocks and Jewellery",
    "95290": "Repair of Personal and Household Goods",
    "96010": "Washing and (Dry-)cleaning of Textile and Fur Products",
    "96020": "Hairdressing and Other Beauty Treatment",
    "96030": "Funeral and Related Activities",
    "96040": "Physical Well-being Activities",
    "96090": "Other Service Activities",

    # T — Households as employers
    "97000": "Activities of Households as Employers of Domestic Personnel",
    "98000": "Undifferentiated Goods and Services-producing Activities of Private Households for Own Use",

    # U — Extraterritorial
    "99000": "Activities of Extraterritorial Organisations and Bodies",

    # Legacy/Other codes sometimes seen in CH data
    "74990": "Non-trading Company",
    "98000": "Residents Property Management",
    "99999": "Dormant Company",
    "00100": "Agriculture",
    "06000": "Extraction of Crude Petroleum and Natural Gas",
    "07100": "Mining of Iron Ores",
    "08110": "Quarrying of Ornamental and Building Stone",
    "89030": "Services to Buildings",
    "89040": "Combined Office Administrative Service Activities",
    "89050": "Other Business Support Service Activities",
    "89060": "Investigation Activities",
    "89070": "Other Service Activities",
    "89080": "Facilities Management Activities",
    "89090": "Other Administrative and Support Service Activities",
    "89100": "Activities of Employment Placement Agencies",
    "89110": "Other Service Activities",
    "89120": "Veterinary Activities",
    "89130": "Cleaning of Buildings and Household",
    "89140": "Retail Sale via Mail Order Houses or via Internet",
    "89150": "Other Food Service Activities",
    "89160": "Retail Sale of Textile, Clothing, Footwear and Leather Goods",
    "89170": "Water Collection, Treatment and Supply",
    "89180": "Management Consultancy Activities",
    "89190": "Other Service Activities not Elsewhere Classified",
    "890173": "Other Service Activities / Services / Contractor",
}


def describe(code: str) -> str:
    """Return 'CODE – Description' or just 'CODE' if not found."""
    code = str(code).strip()
    desc = SIC_DESCRIPTIONS.get(code)
    if desc:
        return f"{code} – {desc}"
    return code


def enrich_sic_codes(codes: list) -> list:
    """Take a list of SIC code strings and return enriched 'CODE – Description' strings."""
    return [describe(c) for c in codes]
