[theme]
base = "light"
primaryColor = "#3d8ef8"
backgroundColor = "#f0f2f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#0d0f14"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
